include core/
include systems/

import gsl = gsl%lib{gsl}

./: core/ systems/
./: lib{mp-units}: lib{mp-units-core} lib{mp-units-systems} $gsl

lib{mp-units}:
{
    cxx.export.libs = lib{mp-units-core} lib{mp-units-systems} $gsl
}
