gsl = # Interface dependencies.
import gsl += gsl%lib{gsl}

lib{mp-units}: hxx{**} $gsl

# Export options.
#
# out_pfx = [dir_path] $out_root/src/core/include/
# src_pfx = [dir_path] $src_root/src/core/include/
core_out_pfx    = [dir_path] $out_root/src/core/include/
core_src_pfx    = [dir_path] $src_root/src/core/include/
systems_out_pfx = [dir_path] $out_root/src/systems/include/
systems_src_pfx = [dir_path] $src_root/src/systems/include/

lib{mp-units}:
{
  cxx.export.poptions = "-I$core_out_pfx" "-I$core_src_pfx" "-I$systems_out_pfx" "-I$systems_src_pfx"
  cxx.export.libs = $gsl
}

# Install recreating subdirectories.
#
hxx{*}:
{
  install         = include/
  install.subdirs = true
}
